/* Zodi Almanac: the 24 solar terms, educational data.
   Traditional characters, tone-marked pinyin. Order = sun longitude from 315 (Li Chun). */
(function (root) {
  "use strict";
  var DATA = { list: [
    { lon: 315, index: 1, hant: "立春", chars: [["立","lì"],["春","chūn"]], pinyin: "lì chūn",
      literal: "spring stands", name: "Spring Begins",
      season: "The traditional first day of spring and the start of the solar year. The cold has not broken yet in northern China, but farmers begin preparing fields, and households once bit into fresh spring rolls or radish in a custom called biting the spring.",
      relevance: "Traditionally a time for fresh starts, so it can be a good stretch to set intentions for the year ahead." },
    { lon: 330, index: 2, hant: "雨水", chars: [["雨","yǔ"],["水","shuǐ"]], pinyin: "yǔ shuǐ",
      literal: "rain water", name: "Rain Water",
      season: "Snow gives way to rain as temperatures climb. Rivers begin to thaw, the soil softens, and this moisture matters for winter wheat waking up in the fields.",
      relevance: "A good stretch to let plans soften and take shape gradually rather than forcing quick results." },
    { lon: 345, index: 3, hant: "驚蟄", chars: [["驚","jīng"],["蟄","zhé"]], pinyin: "jīng zhé",
      literal: "startled hibernators", name: "Insects Awaken",
      season: "The first spring thunder was said to startle hibernating creatures out of the ground. Farmers took it as the signal that busy plowing season had truly begun, and in some regions people ate pears around this term.",
      relevance: "Traditionally a moment when dormant things stir, so it may suit picking a project back up after a long pause." },
    { lon: 0, index: 4, hant: "春分", chars: [["春","chūn"],["分","fēn"]], pinyin: "chūn fēn",
      literal: "spring divides", name: "Spring Equinox",
      season: "Day and night are equal in length, and spring is at its midpoint. Swallows return north, and an old game of balancing an egg upright on this day is still popular.",
      relevance: "A natural point to check whether your work and rest are in reasonable balance." },
    { lon: 15, index: 5, hant: "清明", chars: [["清","qīng"],["明","míng"]], pinyin: "qīng míng",
      literal: "clear and bright", name: "Clear and Bright",
      season: "Skies clear and plants green up in earnest. This term doubles as Qingming Festival, when families sweep ancestral graves, make offerings, and take spring outings.",
      relevance: "Traditionally a time to remember those who came before, so a quiet visit or a phone call to family tends to fit the mood." },
    { lon: 30, index: 6, hant: "穀雨", chars: [["穀","gǔ"],["雨","yǔ"]], pinyin: "gǔ yǔ",
      literal: "grain rain", name: "Grain Rain",
      season: "The last term of spring, named for the rains that feed young grain seedlings. It is prime time for planting rice and cotton, and tea picked just before this term is prized as pre-rain tea.",
      relevance: "A good stretch to give steady attention to something you planted earlier, whether a habit or a plan." },
    { lon: 45, index: 7, hant: "立夏", chars: [["立","lì"],["夏","xià"]], pinyin: "lì xià",
      literal: "summer stands", name: "Summer Begins",
      season: "The traditional start of summer. Crops enter their fast growing season, and in parts of southern China people weighed themselves and ate whole boiled eggs to hold up through the coming heat.",
      relevance: "Traditionally a time to pace yourself for a long busy season rather than sprinting into it." },
    { lon: 60, index: 8, hant: "小滿", chars: [["小","xiǎo"],["滿","mǎn"]], pinyin: "xiǎo mǎn",
      literal: "lesser fullness", name: "Grain Buds",
      season: "Grains in the north begin to plump but are not yet ripe, which is exactly what the name describes. Classical writers liked this term for its restraint: full, but not too full.",
      relevance: "A reminder that almost ripe is its own good stage, so it may be worth letting things mature before you judge them." },
    { lon: 75, index: 9, hant: "芒種", chars: [["芒","máng"],["種","zhòng"]], pinyin: "máng zhòng",
      literal: "bearded grain seeds", name: "Grain in Ear",
      season: "Awned grains like wheat are ready to harvest while rice must be transplanted, so this is the busiest stretch of the farming year. In the south it overlaps the start of the plum rains, the long humid drizzle of early summer.",
      relevance: "A good stretch for focused effort on the one task that genuinely cannot wait." },
    { lon: 90, index: 10, hant: "夏至", chars: [["夏","xià"],["至","zhì"]], pinyin: "xià zhì",
      literal: "summer at its peak", name: "Summer Solstice",
      season: "The longest day of the year in the northern hemisphere. Days begin shortening from here even though the hottest weather is still ahead, and eating noodles on this day is an old custom in northern China.",
      relevance: "Traditionally a peak worth noticing, so it can be a fitting day to appreciate what is going well before conditions shift." },
    { lon: 105, index: 11, hant: "小暑", chars: [["小","xiǎo"],["暑","shǔ"]], pinyin: "xiǎo shǔ",
      literal: "minor heat", name: "Minor Heat",
      season: "Hot weather arrives in force but has not yet peaked. Households traditionally aired out clothes and books in the strong sun to drive off damp and mold.",
      relevance: "A good stretch to lighten your load and clear out what has quietly gathered dust." },
    { lon: 120, index: 12, hant: "大暑", chars: [["大","dà"],["暑","shǔ"]], pinyin: "dà shǔ",
      literal: "major heat", name: "Major Heat",
      season: "The hottest term of the year, falling within the dog days known as sanfu. Thunderstorms are frequent, rice ripens fast, and cooling foods like mung bean soup and herbal teas are the season's staples.",
      relevance: "Traditionally a time to slow down at midday and save your energy for the cooler hours." },
    { lon: 135, index: 13, hant: "立秋", chars: [["立","lì"],["秋","qiū"]], pinyin: "lì qiū",
      literal: "autumn stands", name: "Autumn Begins",
      season: "The traditional start of autumn, even though real heat often lingers in a spell called the autumn tiger. A well known custom is eating rich food to put back the weight lost to summer, known as padding autumn fat.",
      relevance: "A good stretch to start restoring what the busy season wore down, one small comfort at a time." },
    { lon: 150, index: 14, hant: "處暑", chars: [["處","chǔ"],["暑","shǔ"]], pinyin: "chǔ shǔ",
      literal: "heat withdraws", name: "End of Heat",
      season: "The summer heat finally retreats and mornings turn noticeably cooler. Farmers watch ripening crops closely, and along the coast this term traditionally opened the autumn fishing season.",
      relevance: "Traditionally a turning point, so it may suit quietly closing out something that has run its course." },
    { lon: 165, index: 15, hant: "白露", chars: [["白","bái"],["露","lù"]], pinyin: "bái lù",
      literal: "white dew", name: "White Dew",
      season: "Nights are now cool enough that dew condenses on grass and leaves by morning. The name comes from the old association of autumn with the color white, and elders start reminding everyone to cover up at night.",
      relevance: "A gentle cue to add a layer, literally and otherwise, as conditions cool around you." },
    { lon: 180, index: 16, hant: "秋分", chars: [["秋","qiū"],["分","fēn"]], pinyin: "qiū fēn",
      literal: "autumn divides", name: "Autumn Equinox",
      season: "Day and night are equal again and autumn reaches its midpoint. Harvest is in full swing, and since 2018 this date has been marked in China as the Farmers' Harvest Festival.",
      relevance: "A natural moment to take stock of what the year has yielded so far." },
    { lon: 195, index: 17, hant: "寒露", chars: [["寒","hán"],["露","lù"]], pinyin: "hán lù",
      literal: "cold dew", name: "Cold Dew",
      season: "The dew turns cold and can feel near freezing at dawn. Geese fly south, chrysanthemums bloom, and this term often falls near the Double Ninth Festival with its custom of climbing hills.",
      relevance: "A good stretch for brisk walks and unhurried thinking while the air is at its clearest." },
    { lon: 210, index: 18, hant: "霜降", chars: [["霜","shuāng"],["降","jiàng"]], pinyin: "shuāng jiàng",
      literal: "frost descends", name: "Frost Descends",
      season: "The first frosts settle in northern China, ending the growing season. Persimmons ripen to full sweetness now, and an old saying holds that food eaten during this term nourishes better than winter tonics.",
      relevance: "Traditionally a time to finish gathering what matters before the cold sets in." },
    { lon: 225, index: 19, hant: "立冬", chars: [["立","lì"],["冬","dōng"]], pinyin: "lì dōng",
      literal: "winter stands", name: "Winter Begins",
      season: "The traditional start of winter, when the harvest is stored and fieldwork winds down. In northern China families mark the day with dumplings, and the season of rest and preservation begins.",
      relevance: "A good stretch to turn attention inward and set up routines that will carry you through the quiet months." },
    { lon: 240, index: 20, hant: "小雪", chars: [["小","xiǎo"],["雪","xuě"]], pinyin: "xiǎo xuě",
      literal: "minor snow", name: "Minor Snow",
      season: "Light snow begins to fall in the north, though little of it stays on the ground. This is the classic season for preserving food, from curing meats to pickling vegetables for the winter table.",
      relevance: "Traditionally a time for laying things by, so it may suit tidying your reserves of time, money, or energy." },
    { lon: 255, index: 21, hant: "大雪", chars: [["大","dà"],["雪","xuě"]], pinyin: "dà xuě",
      literal: "major snow", name: "Major Snow",
      season: "Snow falls heavier and begins to accumulate in northern China. Farmers welcomed a thick snow cover because it insulates winter wheat and moistens the spring soil, hence the saying that a timely snow promises a good harvest.",
      relevance: "A reminder that some slow, quiet accumulation now can protect what you will need later." },
    { lon: 270, index: 22, hant: "冬至", chars: [["冬","dōng"],["至","zhì"]], pinyin: "dōng zhì",
      literal: "winter at its peak", name: "Winter Solstice",
      season: "The shortest day of the year and one of the most important terms, once celebrated almost like New Year. Families gather to eat dumplings in the north and tangyuan in the south, and from this day the light slowly returns.",
      relevance: "Traditionally a day for gathering close, and a reminder that the darkest point is also where the light turns." },
    { lon: 285, index: 23, hant: "小寒", chars: [["小","xiǎo"],["寒","hán"]], pinyin: "xiǎo hán",
      literal: "minor cold", name: "Minor Cold",
      season: "Deep winter arrives, and in most of China this term is actually colder than Major Cold on average. It falls within the coldest days counted by the traditional nines, and warming meals like laba congee belong to this stretch.",
      relevance: "A good stretch to keep warm, keep routines simple, and not demand too much of yourself or others." },
    { lon: 300, index: 24, hant: "大寒", chars: [["大","dà"],["寒","hán"]], pinyin: "dà hán",
      literal: "major cold", name: "Major Cold",
      season: "The last term of the solar year, named for the depth of winter even as the cycle prepares to turn. Households busy themselves with New Year preparations, cleaning the house and stocking food for the festival.",
      relevance: "Traditionally a time for finishing the year cleanly so the next one can start unburdened." }
  ]};
  root.ALM_TERMS = DATA;
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
})(typeof window !== "undefined" ? window : globalThis);
